openapi: '3.0.3'
info:
  title: Meli
  version: '0.1'
servers:
  - url: https://example.com
paths:
  /ccbs:
    post:
      description: Realiza upload da CCB e enfileira para assinatura
      requestBody:
        content:
          'multipart/form-data':
            schema:
              type: object
              properties:
                number:
                  description: Número da CCB
                  type: string
                content:
                  description: Arquivo PDF
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: object
                properties:
                  key:
                    type: string
                    format: uuid
        '422':
          description: Unprocessable Entity
          content:
            'application/json':
              schema:
                type: array
                items:
                  type: string
                example:
                  - Number is not valid
                  - Number too long
                  - Content is empty
  /cessions:
    post:
      description: Realiza upload da CCB e enfileira para assinatura
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                number:
                  description: Número da Cessão
                  type: string
                ccbs:
                  description: Arquivo PDF
                  type: array
                  items:
                    type: string
                    format: uuid
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: object
                properties:
                  key:
                    type: string
                    format: uuid
        '422':
          description: Unprocessable Entity
          content:
            'application/json':
              schema:
                type: array
                items:
                  type: string
                example:
                  - Number is not valid
                  - Number too long
                  - Content is empty